version: '3.4'

services:
  rabbitmq:
    container_name: rabbit-mq
    image: rabbitmq:3-management-alpine
    volumes:
      - mq_data:/var/lib/rabbitmq/mnesia
    ports:
      - "15672:15672"
      - "5672:5672" 
    networks:
      - chatnetwork

  hellochatapp.botconsole:
    image: hellochatappbotconsole
    depends_on:
      - rabbit-mq
    build:
      context: .
      dockerfile: HelloChatApp.BotConsole/Dockerfile
    networks:
      - chatnetwork

  hellochatapp.server:
    image: hellochatappserver
    depends_on:
      - rabbit-mq
    build:
      context: .
      dockerfile: HelloChatApp/Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "63474:80"
      - "63475:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro      
    networks:
      - chatnetwork

volumes:
  mq_data:

networks:
  chatnetwork:
    driver: bridge